paths:
  save_dir: ../../training_outputs/
  saved_model_path: 
model_settings:
  hidden_channels_GCN: 
    - 32
    - 64
    - 128
    - 256
    - 512
  hidden_channels_MLP: 
    - 512
    - 256
    - 128
    - 64
graph_settings:
  experiment: "z"
  code_size: 5
  repetitions: 5
  min_error_rate: 0.001
  max_error_rate: 0.005
  m_nearest_nodes: 20
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  seed: Null
  dataset_size: 1000000
  validation_set_size: 10000
  batch_size: 20000
  tot_epochs: 300
  lr: 0.0001
  device: cuda
  resume_training: False
  current_epoch: 0
  comment: Nested, no accuracy scaling in loss

