paths:
  save_dir: ../training_outputs/report/
  saved_model_path: ../training_outputs/report/d5_d_t_5_240505-231558.pt
model_settings:
  hidden_channels_GCN:
    - 256
    - 512
  hidden_channels_MLP:
    - 256
    - 128
    - 128
    - 64
graph_settings:
  experiment: "z"
  code_size: 5
  repetitions: 5
  min_error_rate: 0.001
  max_error_rate: 0.001
  m_nearest_nodes: 20
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  seed: Null
  dataset_size: 1000000
  validation_set_size: 60000
  batch_size: 80000
  tot_epochs: 2000
  lr: 0.00001
  device: cuda
  resume_training: True
  current_epoch: 1000
  comment: "Linear layers, continuation test."

