paths:
  save_dir: ../training_outputs/
  saved_model_path: 
graph_settings:
  experiment: "z"
  code_size: 5
  repetitions: 5
  min_error_rate: 0.001
  max_error_rate: 0.005
  one_error_rate: 0.005
  m_nearest_nodes: 20
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  comment: ""
  suffix: "1"
  seed: Null
  dataset_size: 10000 
  batch_size_train: 1000
  validation_set_size: 10000
  batch_size: 20000  # validation set
  n_selections: 50
  repeat_selection: True
  n_repetitions: 12
  search_radius: 0.01
  device: cuda
  resume_training: False
  score_decay: 0.0002
  metric: "balanced"