paths:
  save_dir: ../training_outputs/
  saved_model_path: ../training_outputs/model_240510-112409_2.pt
graph_settings:
  experiment: "z"
  code_size: 5
  repetitions: 5
  min_error_rate: 0.001
  max_error_rate: 0.005
  one_error_rate: 0.001
  m_nearest_nodes: 20
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  comment: "GAT layer 3 heads, score decay 0.0001, search radius 0.05, number of selections 100, mixed p"
  suffix: "2"
  seed: Null
  dataset_size: 500000 
  batch_size_train: 100
  validation_set_size: 40000
  batch_size_val: 100 
  n_selections: 100
  repeat_selection: True
  n_repetitions: 6
  search_radius: 0.05
  device: cuda
  resume_training: False
  score_decay: 0.0001
  metric: "accuracy"