paths:
  save_dir: ../training_outputs/
  saved_model_path: ../training_outputs/d5_d_t_5_240414-212528.pt
model_settings:
  hidden_channels_GCN:
    - 512
    - 512
  hidden_channels_MLP:
    - 256
    - 256
graph_settings:
  experiment: "z"
  code_size: 5
  repetitions: 5
  min_error_rate: 0.001
  max_error_rate: 0.001
  m_nearest_nodes: 20
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  seed: Null
  dataset_size: 1000000
  validation_set_size: 100000
  batch_size: 60000
  tot_epochs: 3000
  lr: 0.000001
  device: cuda
  resume_training: True
  current_epoch: 2000
  comment: "Continuation."
