paths:
  save_dir: ../training_outputs/
  saved_model_path: ../training_outputs/d5_d_t_5_240408-104950_load_f_d5_d_t_5_240403-133555.pt
model_settings:
  hidden_channels_GCN:
    - 256
    - 512
  hidden_channels_MLP:
    - 256
graph_settings:
  experiment: "z"
  code_size: 9
  repetitions: 9
  min_error_rate: 0.001
  max_error_rate: 0.005
  m_nearest_nodes: 20
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  seed: Null
  dataset_size: 1000000
  validation_set_size: 15000
  batch_size: 10000
  tot_epochs: 1500
  lr: 0.00001
  device: cuda
  resume_training: False
  current_epoch: 0
  comment: "Attempt at d = 9."
