paths:
  save_dir: ../training_outputs/
  saved_model_path: ../training_outputs/d5_d_t_5_240316-142335_load_f_d5_d_t_5_240315-152724.pt
graph_settings:
  experiment: "z"
  code_size: 5
  repetitions: 5
  min_error_rate: 0.001
  max_error_rate: 0.005
  one_error_rate: 0.005
  m_nearest_nodes: 20
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  suffix: "a"
  comment: ""
  seed: Null
  dataset_size: 10000
  batch_size_train: 1000
  validation_set_size: 1000
  batch_size: 100  # validation set
  n_selections: 1000
  repeat_selection: False
  n_repetitions: 3
  search_radius: 0.001
  device: cuda
  resume_training: False
  score_decay: 0.0002
  metric: "accuracy"

