paths:
  save_dir: ../training_outputs/
  saved_model_path: ../training_outputs/d5_d_t_5_240316-142335_load_f_d5_d_t_5_240315-152724.pt
model:
  network: GraphNN()
graph_settings:
  experiment: "z"
  code_size: 5
  repetitions: 5
  min_error_rate: 0.001
  max_error_rate: 0.005
  one_error_rate: 0.005
  m_nearest_nodes: 20
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  comment: "0"
  seed: Null
  dataset_size: 10000 # both, should change
  batch_size_train: 1000
  validation_set_size: 10000
  batch_size: 1000  # validation set
  warmup_epochs: 3
  tot_epochs: 10
  n_selections: 100
  repeat_selection: True
  n_repetitions: 3
  search_radius: 0.001
  warmup_lr: 0.001
  lr: 0.0001
  device: cuda
  resume_training: False
  current_epoch: 0

