paths:
  save_dir: ../training_outputs/
  saved_model_path: 
graph_settings:
  experiment: "z"
  code_size: 5
  repetitions: 5
  min_error_rate: 0.001
  max_error_rate: 0.001
  m_nearest_nodes: 20
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  seed: Null
  dataset_size: 30000
  validation_set_size: 10000
  batch_size: 30000
  warmup_epochs: 0
  tot_epochs: 20
  gradient_factor: 2
  warmup_lr: 0.001
  lr: 0.001
  device: cuda:1
  resume_training: False
  current_epoch: 0

