paths:
  save_dir: ../training_outputs/
  saved_model_path: 
model_settings:
  hidden_channels_GCN: 
    - 32
    - 64 
  hidden_channels_MLP: 
    - 64
graph_settings:
  experiment: "z"
  code_size: 9
  repetitions: 9
  min_error_rate: 0.001
  max_error_rate: 0.005
  m_nearest_nodes: 5
  n_node_features: 5
  power: 2
  n_classes: 1
training_settings:
  seed: Null
  dataset_size: 10000
  validation_set_size: 5000
  batch_size: 1000
  tot_epochs: 10
  lr: 0.00001
  device: cuda:1
  resume_training: False
  current_epoch: 0
  comment: "Test"

